import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { catalog } from '../src/data/catalog';

function sql(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

const artEntries = catalog.flatMap((game) => game.characters.flatMap((character) => (
  character.art ? [{ game, character, art: character.art }] : []
)));

const expected = 410;
if (artEntries.length !== expected) {
  throw new Error(`Expected ${expected} reviewed art records in the current art ledger; found ${artEntries.length}.`);
}

const lines: string[] = [
  '-- Generated by scripts/generate-character-art-migration.ts from src/data/promotionalArt.ts.',
  '--',
  '-- Rewrites the art ledger from the shipped records. Every row is re-encoded to WebP at',
  '-- display resolution, so a changed source changes its storage_path or asset_sha256; the',
  '-- superseded rows point at files this release no longer serves and are removed rather than',
  '-- disabled. The table holds catalog rows only, so this is safe to re-run.',
  'begin;',
  '',
  '-- Publisher-owned art mirrored by a community wiki, which grants nothing of its own.',
  'alter table public.character_art_assets',
  "  drop constraint character_art_reuse_mode,",
  "  add constraint character_art_reuse_mode check (asset_reuse_mode in ('express-fan-kit', 'publisher-promotional', 'conditional-fan-kit', 'conditional-community-policy', 'written-permission', 'community-licensed', 'community-mirrored'));",
  '',
  'delete from public.character_art_assets;',
  '',
];

for (const { game, character, art } of artEntries) {
  lines.push(
    'insert into public.character_art_assets (character_id, storage_path, source_url, source_publisher, license_url, asset_reuse_mode, credit_text, permission_evidence, asset_sha256, review_state, is_primary, retrieved_at, reviewed_at, disabled_at)',
    `select c.id, ${sql(art.localPath)}, ${sql(art.sourceUrl)}, ${sql(art.sourcePublisher)}, ${sql(art.reviewUrl)}, ${sql(art.usageBasis)}, ${sql(art.creditText)}, ${sql(art.permissionEvidence)}, ${sql(art.assetHash)}, 'approved', true, ${sql(art.reviewedAt)}, ${sql(art.reviewedAt)}, null`,
    'from public.characters c',
    'join public.game_versions gv on gv.id = c.game_version_id',
    `where gv.slug = ${sql(game.slug)} and c.slug = ${sql(character.slug)} and c.roster_role = ${sql(character.role)}`,
    'on conflict (character_id, asset_sha256) do update set',
    '  storage_path = excluded.storage_path, source_url = excluded.source_url, source_publisher = excluded.source_publisher,',
    '  license_url = excluded.license_url, asset_reuse_mode = excluded.asset_reuse_mode, credit_text = excluded.credit_text,',
    '  permission_evidence = excluded.permission_evidence, review_state = excluded.review_state, is_primary = excluded.is_primary,',
    '  retrieved_at = excluded.retrieved_at, reviewed_at = excluded.reviewed_at, disabled_at = null;',
    '',
  );
}

lines.push(
  `do $$ declare approved integer; begin`,
  `  select count(*) into approved from public.character_art_assets`,
  `  where review_state = 'approved' and is_primary and disabled_at is null;`,
  `  if approved <> ${expected} then`,
  `    raise exception 'Expected ${expected} approved primary art rows, found %', approved;`,
  `  end if;`,
  `end $$;`,
  '',
  'commit;',
  '',
);

await writeFile(
  path.resolve('supabase/migrations/202609200003_complete_character_art.sql'),
  lines.join('\n'),
  'utf8',
);
